""" Abstract Class TrueMeasure """

from abc import ABC
from copy import deepcopy

from .._util import multilevel_constructor, TransformError, univ_repr


class TrueMeasure(ABC):
    """ The True Measure of the Integrand """

    def __init__(self, dimension, transforms, **kwargs):
        """
        Args:
            dimension (ndarray): dimension(s) of the integrand(s)
            kwargs: keyword arguments. keys become attributes
                    with values distributed among object list
        """
        super().__init__()
        measures = multilevel_constructor(self, dimension, transforms=transforms, **kwargs)
        self.measures = measures

    def gen_tm_samples(self, r, n):
        """
        Generate r nxd samples mimicing the TrueMeasure (d = self.dimension
        inferred). This method is a wrapper around gen_dd_samples that applies a
        transform to the result.

        Args:
            r (int): Number of nxd matrices to generate (sample.size()[0])
            n (int): Number of observations (sample.size()[1])


        Returns:
            rxnxd (numpy array) with d being the dimension of the true
            measure space (sample.size()[2])

        Note:
            To initilize this method for each integrand, call ::

                true_measure_obj.set_tm_gen(discrete_distrib_obj)

            This method is not to be called directly on the original
            constructing object.
            Calls to this method should be from the i^th integrand.
            Example call: ::

                true_measure_obj[i].gen_tm_samples(n,r)

        Raises:
            TransformError if this method is called on the original \
            construcing TrueMeasure object or has not \
            been initialized for each true measure yet
        """
        raise TransformError('''
            To initilize this method for each integrand call:
                true_measure_obj.set_tm_gen(discrete_distrib_obj)
            To call this method for the ith integrand call:
                true_measure_obj[i].gen_tm_samples(n,r)
            ''')

    def set_tm_gen(self, discrete_distrib):
        """
        Initialize gen_tm_samples method,
        a method that samples from the discrete_distribution
        and transforms to discrete distribution

        Args:
            discrete_distrib (DiscreteDistribution): the discrete
                distribution samples will be drawn from will use
                discrete_distrib.mimics to select transform from
                self[i].transforms (dict)
        """
        for measure_i in self:
            discrete_distrib_i = deepcopy(discrete_distrib)
            if discrete_distrib_i.mimics not in list(measure_i.transforms.keys()):
                dd_name = type(discrete_distrib_i).__name__
                msr_name = type(measure_i).__name__
                raise TransformError("Cannot tranform %s to %s" % (dd_name, msr_name))
            measure_i.gen_tm_samples = lambda r, n, _self=measure_i: \
                _self.transforms[discrete_distrib_i.mimics][0](_self,
                    discrete_distrib_i.gen_dd_samples(r, n, _self.dimension))

    def set_f(self, integrand, discrete_distrib):
        """
        Initialize f method for each integrand:
        a method that takes in samples generated by gen_tm_samples
        and outputs the integrand samples values

        Args:
            discrete_distrib (DiscreteDistribution): the discrete
                distribution samples will be drawn from.
                discrete_distrib.mimics is uesd as key to
                self[i].transforms (dict)
            integrand (Integrand): the constructing integrand object
        """
        if len(integrand) != len(self):
            raise TransformError("Number of distributions must match number of integrands")
        for integrand_i, measure_i in zip(integrand, self):
            if discrete_distrib.mimics not in list(measure_i.transforms.keys()):
                dd_name = type(discrete_distrib).__name__
                msr_name = type(measure_i).__name__
                raise TransformError("Cannot tranform %s to %s" % (dd_name, msr_name))
            integrand_i.f = lambda x, _self=integrand_i, _msr_obj=measure_i: \
                _msr_obj.transforms[discrete_distrib.mimics][1](_msr_obj, _self.g(x))

    def transform(self, integrand, discrete_distrib):
        """
        Calls self.set_tm_gen(discrete_distrib) then
        calls self.set_f(integrand, discrete_distrib)
        Respectively, these two methods initialize
        true_measure_obj[i].gen_tm_samples(r,n)
        and integrand[i].f(x)
        for i=1,2,...,len(integrand_obj)
        Note: len(integrand_obj)=len(true_measure_obj)

        Args:
            discrete_distrib (DiscreteDistribution): the discrete
                distribution samples will be drawn from.
                discrete_distrib.mimics is uesd as key to
                self[i].transforms (dict)
            integrand (Integrand): the constructing integrand object
        """
        self.set_tm_gen(discrete_distrib)
        self.set_f(integrand, discrete_distrib)

    def __len__(self):
        return len(self.measures)

    def __iter__(self):
        for measure in self.measures:
            yield measure

    def __getitem__(self, i):
        return self.measures[i]

    def __setitem__(self, i, val):
        self.measures[i] = val

    def __repr__(self, attributes=[]):
        """
        Print important attribute values

        Args:
            attributes (list): list of attributes to print

        Returns:
            string of self info
        """
        super_attributes = ['dimension']
        return univ_repr(self, "True Measure", super_attributes + attributes)
