"""Generate MkDocs pages for preserved qmcpy.org paths."""

from __future__ import annotations

import html
import json
import posixpath
from pathlib import Path, PurePosixPath

import yaml


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "data" / "redirects.yml"
DOCS = ROOT / "docs"
MARKER = "Generated by scripts/make_redirect_pages.py"


def validate_path(value: str, field: str) -> PurePosixPath:
    if not value.startswith("/") or not value.endswith("/"):
        raise ValueError(f"{field} must start and end with '/': {value!r}")
    if "?" in value or "#" in value:
        raise ValueError(f"{field} cannot contain a query or fragment: {value!r}")

    path = PurePosixPath(value.strip("/"))
    if not path.parts or any(part in {".", ".."} for part in path.parts):
        raise ValueError(f"{field} is not a safe site path: {value!r}")
    return path


def target_doc_path(target: PurePosixPath) -> PurePosixPath:
    directory_page = DOCS.joinpath(*target.parts, "index.md")
    markdown_page = DOCS.joinpath(*target.parts).with_suffix(".md")
    if directory_page.exists():
        return target / "index.md"
    if markdown_page.exists():
        return PurePosixPath(f"{target.as_posix()}.md")
    raise ValueError(f"redirect target has no documentation source: /{target}/")


def render_page(source: PurePosixPath, target: PurePosixPath, title: str) -> str:
    relative_target = posixpath.relpath(target.as_posix(), source.as_posix()) + "/"
    markdown_target = posixpath.relpath(
        target_doc_path(target).as_posix(), source.as_posix()
    )
    escaped_target = html.escape(relative_target, quote=True)
    script_target = json.dumps(relative_target)
    escaped_title = html.escape(title)

    return f"""---
hide:
  - navigation
  - toc
search:
  exclude: true
---

<!-- {MARKER}; edit data/redirects.yml instead. -->
<meta http-equiv="refresh" content="0; url={escaped_target}">
<script>window.location.replace({script_target});</script>

# Page Moved

This page has moved to [{escaped_title}]({markdown_target}).
"""


def main() -> None:
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    entries = manifest.get("redirects", [])
    seen: set[PurePosixPath] = set()

    for entry in entries:
        source = validate_path(entry["source"], "source")
        target = validate_path(entry["target"], "target")
        title = str(entry["title"]).strip()
        if source in seen:
            raise ValueError(f"duplicate redirect source: /{source}/")
        seen.add(source)

        output = DOCS.joinpath(*source.parts, "index.md")
        if output.exists() and MARKER not in output.read_text(encoding="utf-8"):
            raise RuntimeError(f"refusing to overwrite non-generated page: {output}")
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(render_page(source, target, title), encoding="utf-8")

    print(f"Generated {len(entries)} redirect pages from {MANIFEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
