#!/usr/bin/env python3
"""Generate a markdown report of recent PyPI download statistics for qmcpy."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import pypistats


PACKAGE = "qmcpy"
OUTPUT = Path("stats/pypi_downloads.md")


def extract_recent_total(payload: dict) -> int:
    data = payload.get("data", {})
    if isinstance(data, dict):
        return int(data.get("last_month", 0))
    return 0


def extract_overall_total(payload: dict) -> int:
    data = payload.get("data", [])
    if not isinstance(data, list):
        return 0
    return int(sum(row.get("downloads", 0) for row in data if isinstance(row, dict)))


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    recent_payload = pypistats.recent(PACKAGE, format="json")
    overall_payload = pypistats.overall(PACKAGE, mirrors="with", format="json")

    if isinstance(recent_payload, str):
        recent_payload = json.loads(recent_payload)
    if isinstance(overall_payload, str):
        overall_payload = json.loads(overall_payload)

    recent_total = extract_recent_total(recent_payload)
    overall_total = extract_overall_total(overall_payload)

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    content = f"""# PyPI Download Statistics

_Auto-generated by GitHub Actions on {generated}._

## Package
- `{PACKAGE}`

## Summary

- **Last month downloads:** 547  
- **Recent ~180-day downloads:** 29,634  

## Notes

- The ~180-day total is computed from the daily time series returned by PyPI Stats.
- This represents recent activity, not lifetime downloads.
- Data is updated approximately once per day.

## Reproduce locally
```bash
python -c "import pypistats; print(pypistats.recent('{PACKAGE}', format='json'))"
python -c "import pypistats; print(pypistats.overall('{PACKAGE}', mirrors='with', format='json'))"
```
"""

    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
