from __future__ import annotations

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path


PACKAGE = "qmcpy"
OUTPUT = Path("stats/pypi_downloads.md")


def run_pypistats(args: list[str]) -> dict:
    cmd = ["pypistats", *args, "--format", "json"]
    result = subprocess.run(cmd, check=True, capture_output=True, text=True)
    return json.loads(result.stdout)


def extract_total(payload: dict) -> int:
    data = payload.get("data", [])
    if not data:
        return 0
    if len(data) == 1 and "downloads" in data[0]:
        return int(data[0]["downloads"])
    return int(sum(row.get("downloads", 0) for row in data))


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    recent_payload = run_pypistats(["recent", PACKAGE])
    overall_payload = run_pypistats(["overall", PACKAGE, "--mirrors", "with"])

    recent_total = extract_total(recent_payload)
    overall_total = extract_total(overall_payload)

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    content = f"""# PyPI Download Statistics

_Auto-generated by GitHub Actions on {generated}._

## Package
- `{PACKAGE}`

## Summary
- Downloads in the most recent period reported by `pypistats recent`: **{recent_total:,}**
- Total downloads in the `pypistats overall` report currently returned: **{overall_total:,}**

## Notes
- These numbers come from the `pypistats` package and may reflect PyPI reporting limits and conventions.
- The `recent` and `overall` commands summarize different windows, so their totals should not be interpreted as interchangeable.

## Reproduce locally
```bash
pypistats recent {PACKAGE}
pypistats overall {PACKAGE}
```
"""

    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
