# https://autobencoder.com/2020-08-24-conda-actions/

name: QMCPy_CI

on: [push]

jobs:
  test:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["macos-latest","ubuntu-latest","windows-latest"]
    steps:
    - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: qmcpy
          environment-file: environment.yml
          #python-version: 3.8
          auto-activate-base: false
    - name: Install QMCPy
      run: python -m pip install -e .
    - name: Run Tests
      run: make tests
    - name: Upload to Codecov
      run: |
        python -m coverage xml -i # genereate coverage.xml
        # python -m codecov -t e87cdb03-ccdd-44df-9849-8c5bc460cb9e  # fails without token
        # bash <(curl https://codecov.io/bash)
        curl -s https://codecov.io/bash | bash
