name: QMCPy_CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.13
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        conda env create --file environment.yml
        python -m pip install -e .
    - name: Run Tests
      run: |
        make tests
    - name: Upload to Codecov
      run: |
        python -m coverage xml -i # genereate coverage.xml
        # python -m codecov -t e87cdb03-ccdd-44df-9849-8c5bc460cb9e  # fails without token
        # bash <(curl https://codecov.io/bash)
        curl -s https://codecov.io/bash | bash
