name: Unit Tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
  workflow_dispatch:

concurrency:
  group: unittests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Unit Tests on ${{ matrix.runner }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: macos-15-intel
            python-version: "3.5"
          - runner: macos-15-intel
            python-version: "3.8"
          - runner: macos-15-intel
            python-version: "3.11"
          - runner: macos-15-intel
            python-version: "3.14"
          - runner: ubuntu-20.04
            python-version: "3.6"
          - runner: ubuntu-24.04
            python-version: "3.9"
          - runner: ubuntu-24.04
            python-version: "3.12"
          - runner: windows-latest
            python-version: "3.7"
          - runner: windows-latest
            python-version: "3.10"
          - runner: windows-latest
            python-version: "3.13"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: pip
          cache-dependency-path: |
            requirements/ci-unittests.txt

      - name: Remove old coverage data (Unix)
        if: runner.os != 'Windows'
        run: |
          rm -f .coverage* coverage.json || true

      - name: Remove old coverage data (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Remove-Item -Path .coverage* -Force -ErrorAction SilentlyContinue -Confirm:$false
          Remove-Item -Path coverage.json -Force -ErrorAction SilentlyContinue -Confirm:$false

      - name: Install unit-test dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements/ci-unittests.txt

      - name: Show Python version
        run: |
          python --version
          python -m pip --version

      - name: Run unittests
        run: make unittests
